### PR TITLE
update from just4fun

### PR DESCRIPTION
**Pull request by shm007g**
just update it

### CODE REVIEW

**Comment by shm007g** [comment]
just plain update

**Comment by shm007g** [comment]
I got no write access permission. someone make this pull request true. thx

**Comment by just4fun** [comment]
I just noticed my side project has been forked here and also kept update.

However, this project was created last year and I had no enough time to enhance it during 2016,  since my routine work is quite busy.

Will try to finish basic functionalities in near future.

Thanks for keeping an eye on this project.

**Comment by zackyang000** [comment]
上耍耍班的, 你 busy 啥子 busy.

**Comment by shm007g** [comment]
上面这个人应该要被日

**Comment by just4fun** [comment]
没得意思，太没得意思了。。。
到处都是阿里的人。。。

**Pull request merged**
